config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'


  get 'question_masters/radionew', to: 'question_masters#radionew', as: 'radionew'
  post 'question_masters/radiocreate', to: 'question_masters#radiocreate', as: 'radiocreate'
  
  get 'question_masters/checknew', to: 'question_masters#checknew', as: 'checknew'
  post 'question_masters/checkcreate', to: 'question_masters#checkcreate', as: 'checkcreate'
  
  get 'question_masters/textnew', to: 'question_masters#textnew', as: 'textnew'
  post 'question_masters/textcreate', to: 'question_masters#textcreate', as: 'textcreate'
  delete 'question_masters/textdelete', to: 'question_masters#textdelete', as: 'textdelete'
  
  get 'rankings/answer', to: 'rankings#answer'
  
  post 'answers/:id/new', to: 'answers#create', as: 'answers'
  get 'answers/:id/new', to: 'answers#new', as: 'answer'
  get 'answers/:id/textnew', to: 'answers#textnew', as: 'textnew_a'
  #post 'answers/textcreate', to: 'answers#textcreate', as: 'textcreate_a'
  #delete 'answers/textdelete', to: 'answers#textdelete', as: 'textdelete_a'
  get 'answers/:id/radionew', to: 'answers#radionew', as: 'radionew_a'
  get 'answers/:id/checknew', to: 'answers#checknew', as: 'checknew_a'
  
  resources :users, only: [:show, :new, :create]
  resources :question_masters, only: [:new, :create, :destroy,:show]
  #resources :answers, only: [:new, :create, :destroy]
end

app/models/question_master.rb
class QuestionMaster < ApplicationRecord
  belongs_to :user
  
  validates :question_type, presence: true, length: { maximum: 255 }
  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 255 }
  validates :content, presence: true, length: { maximum: 255 }
  validates :deadline, presence: true
  
 
  has_many :options, inverse_of: :question_master
  has_many :radio_options, class_name: "RadioOption", inverse_of: :question_master
  has_many :check_options, class_name: "CheckOption", inverse_of: :question_master
  accepts_nested_attributes_for :options #, allow_destroy: true
  accepts_nested_attributes_for :radio_options, allow_destroy: true
  accepts_nested_attributes_for :check_options, allow_destroy: true
  
  has_many :answers
  has_many :textanswers, class_name: "TextAnswer"
  has_many :radioanswers, class_name: "RadioAnswer"
  has_many :checkanswers, class_name: "CheckAnswer", inverse_of: :question_master
  accepts_nested_attributes_for :checkanswers, allow_destroy: true
end

app/controllers/question_masters_controller.rb
class QuestionMastersController < ApplicationController
  before_action :logged_in_user
  def new
    @question_master = QuestionMaster.new
    4.times { @question_master.radio_options.build } #追加
  end  

  def create
    @question_master = QuestionMaster.new(question_master_params)
    # question_masterのtype種別が確認できる
    
    # if (@question_master.type == "yyy")
    #   render :radionew
    # elsif (@question_master.type == "xxx")
    #   render :checkboxnew
    # else
    #   render :textnew
    # end
  end

  def destroy
  end
  
  def show
      @question_master = QuestionMaster.find(params[:id])
      if Rails.env.development?
        @answers_rand = @question_master.answers.order("RAND()").limit(5)
      elsif Rails.env.production?
        @answers_rand = @question_master.answers.order("RANDOM()").limit(5)
      end
      @chart_data = @question_master.answers.group(:answer).count
      
      if @question_master.question_type == "Check"
        hash = Hash.new(0)
        @question_master.answers.pluck(:answer).each do |answer|
          JSON.parse(answer).inject(hash){|hash, a| hash[a] += 1; hash}
        end
        @chart_data = hash.select { |key,_| @question_master.options.pluck(:content).include? key }
      end
  end
  
  def textnew
    @question_master = QuestionMaster.new
    @option = Option.new
  end
  
  def textcreate
    @question_master = current_user.question_masters.build(question_master_params)
    if @question_master.save
      flash[:success] = '質問を投稿しました。'
      redirect_to root_url
    else
      @question_master = current_user.question_masters.order('created_at DESC')
      #.page(params[:page])
      flash.now[:danger] = '質問の投稿に失敗しました。'
      render 'toppages/index'
    end
  end
  
  def textdelete
  end
  
  def radionew
    @question_master = QuestionMaster.new
    4.times { @question_master.radio_options.build } #追加
  end
  
  def radiocreate
    @question_master = current_user.question_masters.new(radiocreate_params)
    
    if @question_master.save
      flash[:success] = '質問を投稿しました。'
      redirect_to root_url
    else
      #@question_master = current_user.question_masters.order('created_at DESC')
      #.page(params[:page])
      flash.now[:danger] = '質問の投稿に失敗しました。'
      render :radionew
    end
  end
  
  def checknew
    @question_master = QuestionMaster.new
    4.times { @question_master.check_options.build } #追加
  end
  
  def checkcreate
    @question_master = current_user.question_masters.new(checkcreate_params)
    
    if @question_master.save
      flash[:success] = '質問を投稿しました。'
      redirect_to root_url
    else
      #@question_master = current_user.question_masters.order('created_at DESC')
      #.page(params[:page])
      flash.now[:danger] = '質問の投稿に失敗しました。'
      render :radionew
    end
  end

  private

  def radiocreate_params
    params.require(:question_master).permit(:question_type, :user_id, :title, :content, :deadline,
                                            radio_options_attributes: [:content])
  end
  
  def checkcreate_params
    params.require(:question_master).permit(:question_type, :user_id, :title, :content, :deadline,
                                            check_options_attributes: [:content])
  end

  def question_master_params
    params.require(:question_master).permit(:question_type, :user_id, :title, :content, :deadline)
  end
  
  def option_params
  end
  
end

app/views/question_masters/_check_option_form.html.erb
<div class="form-group">
   <%= check_options_fields.label :content, '回答' + num.to_s %>
  <div class="form-inline">
    <%= check_options_fields.link_to_remove do %>
      <i class="fa fa-minus-square-o"></i>
    <% end %>
    <%= check_options_fields.text_field :content, class: 'form-control' %>
  </div>
</div>

app/views/question_masters/_check_option_fotm.html.erb
<div class="form-group">
   <%= check_options_fields.label :content, '回答' + num.to_s %>
  <div class="form-inline">
    <%= check_options_fields.link_to_remove do %>
      <i class="fa fa-minus-square-o"></i>
    <% end %>
    <%= check_options_fields.text_field :content, class: 'form-control' %>
  </div>
</div>

app/views/question_masters/_checknew.html.erb
<div class="row">
  <div class="col-xs-offset-1 col-xs-10">
    <% if @question_master.present? %>
      <%= render 'error_messages', model: @question_master %>
    <% end %>
    
    <%= nested_form_for(@question_master, url:{action:'checkcreate'}) do |f| %>

      <%= f.hidden_field :question_type, value: 'Check' %>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <div class="form-group">
        <%= f.label :title, 'タイトル' %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :content, '内容' %>
        <%= f.text_area :content, class: 'form-control' %>
      </div>
      
      
      <% num = 0 %>
      <%= f.fields_for :check_options do |check_options_fields| %>
        <% num += 1 %>
          <%= render 'check_option_form',check_options_fields:check_options_fields, num:num%>
      <% end %>
      <%= f.link_to_add(:check_options)  do %>
        <i class="fa fa-plus-square-o"></i> 回答を追加
      <% end %>
      
      <div class="form-group">
        <%= f.label :deadline, '期限' %>
        <%= f.datetime_select :deadline, class: 'form-control' , :use_month_numbers => true %>
      </div>
      
      <div class="text-center">
        <%= f.submit '投稿する', class: 'btn btn-info' %>
      </div>
    <% end %>
  </div>
</div>

app/views/question_masters/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/question_masters/_radio_option_form.html.erb
<div class="form-group">
  <%= radio_options_fields.label :content, '選択肢' + num.to_s %>
  <div class="form-inline">
    <%= radio_options_fields.link_to_remove do %>
      <i class="fa fa-minus-square-o"></i>
    <% end %>
    <%= radio_options_fields.text_field :content, class: 'form-control' %>
  </div>
</div>

app/views/question_masters/_radionew.html.erb
<div class="row">
  <div class="col-xs-offset-1 col-xs-10">
    <% if @question_master.present? %>
      <%= render 'error_messages', model: @question_master %>
    <% end %>
    
    <%= nested_form_for(@question_master, url:{action:'radiocreate'}) do |f| %>

      <%= f.hidden_field :question_type, value: 'Radio' %>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <div class="form-group">
        <%= f.label :title, 'タイトル' %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :content, '内容' %>
        <%= f.text_area :content, class: 'form-control' %>
      </div>
      
      <% num = 0 %>
      <%= f.fields_for :radio_options do |radio_options_fields| %>
        <% num += 1 %>
          <%= render 'radio_option_form',radio_options_fields:radio_options_fields, num:num %>
      <% end %>
      <%= f.link_to_add(:radio_options)  do %>
        <i class="fa fa-plus-square-o"></i> 選択肢を追加
      <% end %>
      
      <div class="form-group">
        <%= f.label :deadline, '期限' %>
        <%= f.datetime_select :deadline, class: 'form-control' , :use_month_numbers => true %>
      </div>
      
      <div class="text-center">
        <%= f.submit '投稿する', class: 'btn btn-info' %>
      </div>
    <% end %>
  </div>
</div>

app/views/question_masters/_textnew.html.erb
<div class="row">
  <div class="col-xs-offset-1 col-xs-10">
    <%= form_for(@question_master, url:{action:'textcreate'}) do |f| %>

      <%= f.hidden_field :question_type, value: 'Text' %>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <div class="form-group">
        <%= f.label :title, 'タイトル' %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :content, '内容' %>
        <%= f.text_area :content, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :deadline, '期限' %>
        <%= f.datetime_select :deadline, class: 'form-control' , :use_month_numbers => true %>
      </div>
      
      <div class="text-center">
        <%= f.submit '投稿する', class: 'btn btn-info' %>
      </div>
    <% end %>
  </div>
</div>

app/views/question_masters/checknew.js.erb
$(".tabs-content").html("<%= escape_javascript(render 'checknew') %>");
$(".tabs-menu li").removeClass("active");
$(".tabs-menu .checktab").parent("li").addClass("active");
$(".tabs-content").css('background','#dbebf8');

app/views/question_masters/create.html.erb
<h1>QuestionMasters#create</h1>
<p>Find me in app/views/question_masters/create.html.erb</p>

app/views/question_masters/destroy.html.erb
<h1>QuestionMasters#destroy</h1>
<p>Find me in app/views/question_masters/destroy.html.erb</p>

app/views/question_masters/new.html.erb
<div class="row">
  <div class="col-xs-12">
    <div class="panel panel-default">
      <div class="panel-heading">新規質問投稿</div>
      <div class="panel-body">
        
        <div class="tabs-menu">
          <ul>
            <li class="active"><%= link_to "ラジオボタンタイプ", radionew_path, :remote => true, :class =>'tab radiotab' %></li>
            <li><%= link_to 'チェックボックスタイプ', checknew_path, :remote => true, :class =>'tab checktab' %></li>
            <li><%= link_to 'テキストボックスタイプ', textnew_path, :remote => true, :class =>'tab texttab' %></li>
          </ul>
        </div>
        
        <div class="tabs-content">
          <%= render 'radionew' %>
        </div>
        
      </div>
    </div>
  </div>
</div>

app/views/question_masters/radionew.js.erb
$(".tabs-content").html("<%= escape_javascript(render 'radionew') %>");
$(".tabs-menu li").removeClass("active");
$(".tabs-menu .radiotab").parent("li").addClass("active");
$(".tabs-content").css('background','#F8DBEB');

app/views/question_masters/show.html.erb
<div class="row">
  <div class="col-xs-offset-1 col-xs-10">
    <div class="panel panel-default">
      <div class="panel-heading"><h1><%= @question_master.title %></h1></div>
      <div class="panel-body">
         <p><%= @question_master.content %></p>
          <% if @question_master.question_type == "Text" %>
            <% path = textnew_a_path(@question_master.id) %>
            <p>回答例</p>
            <ul class="list-group">
              <% @answers_rand.each do |answer| %>
            	  <li class="list-group-item"><%= answer.answer %></li>
            	<% end %>
            </ul>

          <% elsif @question_master.question_type == "Radio" %>
            <% path = radionew_a_path(@question_master.id) %>
            <p>現在の集計結果</p>
            <%= pie_chart @chart_data %>
            
          <% elsif @question_master.question_type == "Check" %>
            <% path = checknew_a_path(@question_master.id) %>
            <p>現在の集計結果</p>
            <%= column_chart @chart_data %>
          <% end %>

          <% #if !@question_master.answers.find_by(user_id: current_user) %>
            <%= link_to "回答する", path, class:'btn btn-primary' %>
          <% #else %>
            <button class="btn btn-default">回答済み</button>
          <% #end %>
      </div>
    </div>
  </div>
</div>  
  
  
  

app/views/question_masters/textnew.js.erb
$(".tabs-content").html("<%= escape_javascript(render 'textnew') %>");
$(".tabs-menu li").removeClass("active");
$(".tabs-menu .texttab").parent("li").addClass("active");
$(".tabs-content").css('background','#DDF8DB');