config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'


  get 'question_masters/radionew', to: 'question_masters#radionew', as: 'radionew'
  post 'question_masters/radiocreate', to: 'question_masters#radiocreate', as: 'radiocreate'
  
  get 'question_masters/checknew', to: 'question_masters#checknew', as: 'checknew'
  post 'question_masters/checkcreate', to: 'question_masters#checkcreate', as: 'checkcreate'
  
  get 'question_masters/textnew', to: 'question_masters#textnew', as: 'textnew'
  post 'question_masters/textcreate', to: 'question_masters#textcreate', as: 'textcreate'
  delete 'question_masters/textdelete', to: 'question_masters#textdelete', as: 'textdelete'
  
  get 'rankings/answer', to: 'rankings#answer'
  
  post 'answers/:id/new', to: 'answers#create', as: 'answers'
  get 'answers/:id/new', to: 'answers#new', as: 'answer'
  get 'answers/:id/textnew', to: 'answers#textnew', as: 'textnew_a'
  #post 'answers/textcreate', to: 'answers#textcreate', as: 'textcreate_a'
  #delete 'answers/textdelete', to: 'answers#textdelete', as: 'textdelete_a'
  get 'answers/:id/radionew', to: 'answers#radionew', as: 'radionew_a'
  get 'answers/:id/checknew', to: 'answers#checknew', as: 'checknew_a'
  
  resources :users, only: [:show, :new, :create]
  resources :question_masters, only: [:new, :create, :destroy,:show]
  #resources :answers, only: [:new, :create, :destroy]
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    @question_masters = QuestionMaster.all.order('created_at DESC')
  
    @ranking_counts = Answer.ranking
    @question_masters_rank = QuestionMaster.find(@ranking_counts.keys)
    @question_masters_limit = QuestionMaster.where('deadline >= ?', Time.now).limit(5)
  end
end

app/views/toppages/index.html.erb
<div class="row">
  <div class="col-sm-8 col-xs-12">
    <div class="panel panel-default">
      <div class="panel-heading"><h1>最新の質問一覧</h1></div>
      <div class="panel-body">
          <ul class="media-list list-group">
            <% @question_masters.each do |question_master| %>
              <% user = question_master.user %>
                <li class="media">
                  <div class="media-left">
                    <img class="media-object img-rounded" src="<%= gravatar_url(user, options = { size: 50 }) %>" alt="">
                  </div>
                  <div class="media-body">
                    <div>
                      <%= link_to user.name, user_path(user) %>さんの質問 <span class="text-muted">　投稿日: <%= question_master.created_at.strftime("%Y-%m-%d %H:%M:%S") %></span>
                    </div>
                    <div>
                      <p>
                        <%= link_to question_master.title, question_master %>
                        <% if question_master.question_type == "Text" %>
                          <span class="type_name type_name_text">テキストボックス</span>
                        <% elsif question_master.question_type == "Radio" %>
                          <span class="type_name type_name_radio">ラジオボタン</span>
                        <% elsif question_master.question_type == "Check" %>
                          <span class="type_name type_name_check">チェックリスト</span>
                        <% end %>
                      </p>
                    </div>
                  </div>
                </li>
          	<% end %>
          </ul>
          <% unless logged_in? %>
            <%= link_to '新規登録', signup_path, class: 'btn btn-success btn-lg' %>
          <% end %>
      </div>
    </div>
  </div>
        <!-- left -->
        <div class="col-sm-4 col-xs-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    人気ランキング
                </div>
                <ul class="nav nav-pills nav-stacked">
                    <% rank_num = 1 %>
                    <% @question_masters_rank.each do |question_master| %>
                      <li>
                        <%= link_to question_master, :method => :get do %>
                          <i class="fa fa-trophy" aria-hidden="true"></i><%= rank_num %>．<%= question_master.title %>
                        <% end %>
                      </li>
                      <% rank_num += 1 %>
                    <% end %>
                </ul> 
            </div>
        </div>
        
        <div class="col-sm-4 col-xs-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    期限が近い質問
                </div>
                <ul class="nav nav-pills nav-stacked">
                  <% if @question_masters_limit.count==0 %>
                    <li>
                      <a>現在期限が近い質問はありません。</a>
                    </li>
                  <% elsif @question_masters_limit.count!=0 %>
                    <% @question_masters_limit.each do |question_master| %>
                        <% user = question_master.user %>
                        <% deadline = question_master.deadline.to_datetime %>
                        <% today = DateTime.now %>
                        <% diff = deadline-today %>
                        <% day = diff.to_i %>
                        <% hour = ((diff-day)*24).to_i %>
                        <% min = ((diff-day-(hour/24))*60).to_i %>
                        <% sec = ((diff-day-(hour/24)-(min/60))*60).to_i %>
                        <li>
                          <% limit = "残り" + day.to_s + "日" + hour.to_s + "時間" + min.to_s + "分" + sec.to_s + "秒" %>
                          <%= link_to question_master.title + ' ', question_master %>
                          <a class="deadline" data-deadline="<%= deadline %>"></a>
                        </li>
                    	<% end %>
                  	<% end %>
                </ul> 
            </div>
        </div>
</div>