config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'


  get 'question_masters/radionew', to: 'question_masters#radionew', as: 'radionew'
  post 'question_masters/radiocreate', to: 'question_masters#radiocreate', as: 'radiocreate'
  
  get 'question_masters/checknew', to: 'question_masters#checknew', as: 'checknew'
  post 'question_masters/checkcreate', to: 'question_masters#checkcreate', as: 'checkcreate'
  
  get 'question_masters/textnew', to: 'question_masters#textnew', as: 'textnew'
  post 'question_masters/textcreate', to: 'question_masters#textcreate', as: 'textcreate'
  delete 'question_masters/textdelete', to: 'question_masters#textdelete', as: 'textdelete'
  
  get 'rankings/answer', to: 'rankings#answer'
  
  post 'answers/:id/new', to: 'answers#create', as: 'answers'
  get 'answers/:id/new', to: 'answers#new', as: 'answer'
  get 'answers/:id/textnew', to: 'answers#textnew', as: 'textnew_a'
  #post 'answers/textcreate', to: 'answers#textcreate', as: 'textcreate_a'
  #delete 'answers/textdelete', to: 'answers#textdelete', as: 'textdelete_a'
  get 'answers/:id/radionew', to: 'answers#radionew', as: 'radionew_a'
  get 'answers/:id/checknew', to: 'answers#checknew', as: 'checknew_a'
  
  resources :users, only: [:show, :new, :create]
  resources :question_masters, only: [:new, :create, :destroy,:show]
  #resources :answers, only: [:new, :create, :destroy]
end

app/models/answer.rb
class Answer < ApplicationRecord
  validates :type, presence: true, length: { maximum: 50 }
  validates :question_master_id, presence: true
  validates :user_id, presence: true
  validates :answer, presence: true, length: { maximum: 255 }
  
  belongs_to :question_master
  belongs_to :user
  
  def self.ranking
    self.group(:question_master_id).order('count_question_master_id DESC').limit(5).count(:question_master_id)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/check_answer.rb
class CheckAnswer < Answer
end

app/models/check_option.rb
class CheckOption < Option
end

app/models/option.rb
class Option < ApplicationRecord
  validates :type, presence: true, length: { maximum: 50 }
  validates :content, presence: true, length: { maximum: 255 }
  
  belongs_to :question_master, inverse_of: :options
end

app/models/question_master.rb
class QuestionMaster < ApplicationRecord
  belongs_to :user
  
  validates :question_type, presence: true, length: { maximum: 255 }
  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 255 }
  validates :content, presence: true, length: { maximum: 255 }
  validates :deadline, presence: true
  
 
  has_many :options, inverse_of: :question_master
  has_many :radio_options, class_name: "RadioOption", inverse_of: :question_master
  has_many :check_options, class_name: "CheckOption", inverse_of: :question_master
  accepts_nested_attributes_for :options #, allow_destroy: true
  accepts_nested_attributes_for :radio_options, allow_destroy: true
  accepts_nested_attributes_for :check_options, allow_destroy: true
  
  has_many :answers
  has_many :textanswers, class_name: "TextAnswer"
  has_many :radioanswers, class_name: "RadioAnswer"
  has_many :checkanswers, class_name: "CheckAnswer", inverse_of: :question_master
  accepts_nested_attributes_for :checkanswers, allow_destroy: true
end

app/models/radio_answer.rb
class RadioAnswer < Answer
end

app/models/radio_option.rb
class RadioOption < Option
end

app/models/text_answer.rb
class TextAnswer < Answer
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  validates :age, presence: true, numericality: {
            only_integer: true, greater_than_or_equal_to: 0,
            less_than_or_equal_to: 150
          }
  validates :sex, presence: true, length: { maximum: 10 }
  has_secure_password
  
  has_many :question_masters
  has_many :answers
  has_many :text_answers
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  
  def new
    @question_master = QuestionMaster.find(params[:id])
    if @question_master == "TextAnswer"
      redirect_to textnew_a_path(params[:id])
    end
  end
  
  def textnew
    @question_master = QuestionMaster.find(params[:id])
  end
  
  def radionew
    @question_master = QuestionMaster.find(params[:id])
    @options = @question_master.options
  end
  
  def checknew
    @question_master = QuestionMaster.find(params[:id])
    @options = @question_master.options
  end

  def create
    @question_master = QuestionMaster.find(params[:answer][:question_master_id])
    if (params[:answer][:type] == "Text")
      @answer = @question_master.textanswers.build(answer_params)
    elsif (params[:answer][:type] == "Radio")
      @answer = @question_master.radioanswers.build(answer_params)
    elsif (params[:answer][:type] == "Check")
      @answer = @question_master.checkanswers.build(checkanswer_params)
    end
    if @answer.save
      flash[:success] = '正常に回答されました'
      redirect_to @question_master
    else
      flash.now[:danger] = '正常に回答されませんでした'
      render :new
    end
  end

  def destroy
  end
  
  private

  # Strong Parameter
  def answer_params
    params.require(:answer).permit(:question_master_id,:answer,:user_id)
  end
  
  def checkanswer_params
    params.require(:answer).permit(:question_master_id,{:answer => []},:user_id)
  end
  
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  def index
    #@question_master = QuestionMaster.find(params[:id])
    #@chart_data = QuestionMaster.find(params[:id]).answers.group(:answer).count
    @chart_data = Model.order('date ASC').group(:date).count
  end
end

app/controllers/rankings_controller.rb
class RankingsController < ApplicationController
  def answer
    @ranking_counts = Answer.ranking
    @question_masters_rank = QuestionMaster.find(@ranking_counts.keys)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    @question_masters = QuestionMaster.all.order('created_at DESC')
  
    @ranking_counts = Answer.ranking
    @question_masters_rank = QuestionMaster.find(@ranking_counts.keys)
    @question_masters_limit = QuestionMaster.where('deadline >= ?', Time.now).limit(5)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :email, :sex, :age, :password, :password_confirmation)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
  
  def store_location
    session[:forwarding_url] = request.url if request.get?
  end  
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}&d=mm"
  end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <%= message %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="text-center text-muted">© 2017 OPINIONS.</div>
</footer>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-default navbar-static-top">
    <div class="container">
      <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-left" href="/"><%= image_tag("/images/logo.png", alt:"opinions", size:"300x65") %></a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to '質問投稿', new_question_master_path %></li>
          <li><%= link_to 'ログアウト', logout_path, method: :delete %></li>
        <% else %>
          <li><%= link_to '新規登録', signup_path %></li>
          <li><%= link_to 'ログイン', login_path %></li>
        <% end %>
      </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title>Opinions</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= include_gon %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
    <%= javascript_include_tag "jquery.clock.js" %>
    
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= render 'layouts/flash_messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>